[package]
name = "better-commands"
description = "Better commands - get stdout and stderr together, with timestamps"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
keywords = ["command", "cmd"]

[dependencies]
